# Generated by Django 4.2.1 on 2023-05-13 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('link_status', models.BooleanField(default=False)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bot')),
                ('type_id', models.ManyToManyField(to='api.typecommand')),
            ],
        ),
    ]
