# Generated by Django 4.2.1 on 2023-05-15 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_commandcall_command_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(default=None, max_length=255)),
                ('file', models.TextField()),
                ('command_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.command')),
            ],
        ),
    ]
