# Generated by Django 4.2.1 on 2023-05-15 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_media_command_id_messagecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('command_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailCommand', to='api.command')),
            ],
        ),
    ]
