# Generated by Django 4.2.1 on 2023-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mailcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcommand',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
