# Generated by Django 4.2.1 on 2023-05-15 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_mailcommand_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=32)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bot')),
            ],
        ),
    ]
