# Generated by Django 4.2.1 on 2023-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_linkcommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcommand',
            name='follow',
        ),
        migrations.AddField(
            model_name='linkcommand',
            name='follow',
            field=models.ManyToManyField(related_name='follow', to='api.command'),
        ),
    ]
