# Generated by Django 4.2.1 on 2023-05-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_bot_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='type_id',
        ),
        migrations.AddField(
            model_name='command',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.typecommand'),
        ),
    ]
