# Generated by Django 4.2.1 on 2023-05-19 15:23

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_command_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=api.models.Bot),
        ),
    ]
