# Generated by Django 4.2.1 on 2023-05-19 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_command_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
